// AUTO-GENERATED by scripts/optimize-assets.mjs — do not edit by hand.
// Re-run `npm run assets:landing` after adding or changing source art.

import logoColors from "./logo-colors.webp";
import logoWordBlack from "./logo-word-black.webp";
import logoWordWhite from "./logo-word-white.webp";
import mascotHi from "./mascot-hi.webp";
import mascotHat from "./mascot-hat.webp";
import mascotLearning from "./mascot-learning.webp";
import mascotSmart from "./mascot-smart.webp";
import mascotCool from "./mascot-cool.webp";
import mascotShrug from "./mascot-shrug.webp";
import mascotCoolBust from "./mascot-cool-bust.webp";
import mascotPractical from "./mascot-practical.webp";
import mascotCoins from "./mascot-coins.webp";
import mascotOpportunities from "./mascot-opportunities.webp";
import coin from "./coin.webp";
import floatSpark from "./float-spark.webp";
import floatCap from "./float-cap.webp";
import floatHeadset from "./float-headset.webp";
import floatConfetti from "./float-confetti.webp";
import floatWave from "./float-wave.webp";
import floatFocus from "./float-focus.webp";

export interface LandingImage {
  src: string;
  width: number;
  height: number;
}

export const landingImages: Record<string, LandingImage> = {
  "logo-colors": { src: logoColors, width: 1100, height: 338 },
  "logo-word-black": { src: logoWordBlack, width: 420, height: 135 },
  "logo-word-white": { src: logoWordWhite, width: 420, height: 135 },
  "mascot-hi": { src: mascotHi, width: 606, height: 900 },
  "mascot-hat": { src: mascotHat, width: 498, height: 900 },
  "mascot-learning": { src: mascotLearning, width: 760, height: 697 },
  "mascot-smart": { src: mascotSmart, width: 538, height: 900 },
  "mascot-cool": { src: mascotCool, width: 316, height: 900 },
  "mascot-shrug": { src: mascotShrug, width: 640, height: 615 },
  "mascot-cool-bust": { src: mascotCoolBust, width: 640, height: 877 },
  "mascot-practical": { src: mascotPractical, width: 620, height: 900 },
  "mascot-coins": { src: mascotCoins, width: 700, height: 884 },
  "mascot-opportunities": { src: mascotOpportunities, width: 658, height: 900 },
  "coin": { src: coin, width: 256, height: 271 },
  "float-spark": { src: floatSpark, width: 220, height: 346 },
  "float-cap": { src: floatCap, width: 280, height: 184 },
  "float-headset": { src: floatHeadset, width: 240, height: 280 },
  "float-confetti": { src: floatConfetti, width: 240, height: 263 },
  "float-wave": { src: floatWave, width: 220, height: 188 },
  "float-focus": { src: floatFocus, width: 220, height: 195 },
};
